### PR TITLE
Setup GitHub Actions to create auto releases

### PR DESCRIPTION
**Pull request by GXTX**
This will create releases automatically when changes are pushed to the master branch and will also check if the project builds during new PR's.

Also your builds were so huge because you were building in debug or something, no clue why they're almost 200MB

### CODE REVIEW

**Review by Vauff — CHANGES_REQUESTED** [review]
Thanks for setting this up, however shipping a release for every master push doesn't really fit the workflow of this project, due to the frequent servers.json edits not being an actual part of the codebase. I've never messed with GitHub's CI before, so I'm not sure what alternatives are possible here. Ideally I could just manually push a release based upon a CI build.

The current builds are so large because they bundle .NET Core with them, I tried to run the smaller binaries generated in your fork and wasn't getting anything to open.

**Comment by GXTX** [comment]
> The current builds are so large because they bundle .NET Core with them, I tried to run the smaller binaries generated in your fork and wasn't getting anything to open.

That makes sense, we can switch the build command to generate the "proper" executable. You not being able to open is likely because you don't have .NET core installed. Interestingly the reason I am even playing with any of this is I couldn't get the larger exe to actually launch.

> due to the frequent servers.json edits not being an actual part of the codebase

I'm not sure it makes sense to *not* create a release when this is updated. The downloader is dependent on the information in this file and *not* creating a release would likely introduce a instance where a user has an outdated link so he/she would get a 404 while trying to download.

You had asked if we can actually skip running on these specific changes and the answer is yes we can ignore changes for specific files or folders but I disagree with that specific file being ignored. We could set an ignore for say `readme` or `license`, no problem.

**Comment by Vauff** [comment]
> I'm not sure it makes sense to _not_ create a release when this is updated. The downloader is dependent on the information in this file and _not_ creating a release would likely introduce a instance where a user has an outdated link so he/she would get a 404 while trying to download.

servers.json is not bundled in the shipped release, the program dynamically pulls the latest version from GitHub on every startup (https://github.com/Vauff/MapDownloader/blob/master/MapDownloader/FrmStartup.cs#L30). That's why it doesn't make sense to trigger builds for it.

**Comment by GXTX** [comment]
Went ahead and added the ignores as requested. I still did not change to have .NET bundle with the application - it feels dirty. You can change this before or after merge if you wish, the PR is set to allow maintainers edit access.

**Review by Vauff — APPROVED** [review]

**Pull request merged**
